# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loading_window_design_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_loading_window(object):
    """Initialization window design:"""
    def __init__(self,Screen_height, Screen_width):
        self.screen_height = Screen_height
        self.screen_width = Screen_width
    def setupUi(self, MainWindow):
        width_scale = int(self.screen_width / 1920)
        height_scale = int(self.screen_height / 1030)
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowIcon(QtGui.QIcon('running_files/images/vetruv_ico.ico'))
        MainWindow.resize(width_scale *482, height_scale *536)
        MainWindow.setMinimumSize(QtCore.QSize(width_scale *482, height_scale *556))
        MainWindow.setMaximumSize(QtCore.QSize(width_scale *482, height_scale *556))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30 *width_scale, 20 *height_scale, 420*width_scale, 520*height_scale))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")

        self.pushButton_start = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_start.setGeometry(QtCore.QRect(20*width_scale, 460*height_scale, 380*width_scale, 40*height_scale))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setObjectName("pushButton_start")

        self.label_vettruve = QtWidgets.QLabel(self.groupBox)
        self.label_vettruve.setGeometry(QtCore.QRect(60*width_scale, 40*height_scale, 300*width_scale, 300*height_scale))
        self.label_vettruve.setText("")
        self.label_vettruve.setPixmap(QtGui.QPixmap("running_files/images/vetruv_png.png"))
        self.label_vettruve.setScaledContents(True)
        self.label_vettruve.setObjectName("label_vettruve")

        self.label_loading_language = QtWidgets.QLabel(self.groupBox)
        self.label_loading_language.setGeometry(QtCore.QRect(50*width_scale, 360*height_scale, 320*width_scale, 31*height_scale))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_loading_language.setFont(font)
        self.label_loading_language.setObjectName("label_loading_language")

        self.radioButton_pose_estimator = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(40)
        self.radioButton_pose_estimator.setFont(font)
        self.radioButton_pose_estimator.setObjectName("radioButton_pose_estimator")
        self.radioButton_pose_estimator.setGeometry(QtCore.QRect(120, 400, 200, 20))

        self.radioButton_sequence_selector = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_sequence_selector.setFont(font)
        self.radioButton_sequence_selector.setObjectName("radioButton_sequence_selector")
        self.radioButton_sequence_selector.setGeometry(QtCore.QRect(120, 425, 200, 20))

        self.pushButton_french = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_french.setGeometry(QtCore.QRect(450*width_scale, 0*height_scale, 30*width_scale, 20*height_scale))
        self.pushButton_french.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("running_files/images/french.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_french.setIcon(icon)
        self.pushButton_french.setIconSize(QtCore.QSize(40*width_scale, 30*height_scale))
        self.pushButton_french.setObjectName("pushButton_french")

        self.pushButton_english = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_english.setGeometry(QtCore.QRect(415*width_scale, 0*height_scale, 30*width_scale, 20*height_scale))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.pushButton_english.setFont(font)
        self.pushButton_english.setAutoFillBackground(False)
        self.pushButton_english.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("running_files/images/english.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_english.setIcon(icon1)
        self.pushButton_english.setIconSize(QtCore.QSize(40*width_scale, 50*height_scale))
        self.pushButton_english.setAutoDefault(False)
        self.pushButton_english.setDefault(False)
        self.pushButton_english.setObjectName("pushButton_english")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AGMA-PESS"))

